# Оновные параметры
model: "yolov8m.pt" # Тип модели
iou: 0.55 # Пороговое значение метрики IoU для учета предсказания модели.
conf: 0.5 # Порог степени уверенности модели в предсказании для отнесения к предсказываемому классу
video_path: "../data/crowd.mp4" # Путь к видео для обработки
save_path: "../output/detected_video.mp4" # Путь для сохранения обработанного видео
weights_path: "../weigths/yolov8m.pt" # Путь к весам модели

# Параметры отображения а видео
line_width: 2 # Ширина линии bounfing box
font_size: 0.8 # Размер шрифта для отображения названия класса
labels: True # Флаг для отображения названий классов на видео
boxes: True # Флаг для отображния bounding box на видео
